### ISSUE TITLE
issues installation

### ISSUE THREAD

**Issue by MangeStrandberg** [XMBomb/InComb#22]
Hi,

get this message when trying to go through the steps:
## How to run InComb
1. Create a new MySQL database from the schema in `src/main/sql/schema.sql`
2. Execute `src/main/sql/data.sql`
3. Adjust your settings in `WebContent/WEB-INF/conf/incomb_config.json`

Get this when running step 2.
#1452 - Cannot add or update a child row: a foreign key constraint fails (`incomb`.`fly_with`, CONSTRAINT `fk_User_has_User_User1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)

Any ideas?

thanks

**Comment by marcsieber** [comment]
Can you post the specific SQL statement which triggers your error?

**Comment by MangeStrandberg** [comment]
INSERT INTO `fly_with` (`user_id`, `fly_with_id`, `fly_with_start_date`) VALUES (1, 2, '2015-01-04 01:26:34')

I also noticed that 'Priamry Key' 1 is casuing issues as it is stated in more than one statement.

**Comment by marcsieber** [comment]
It looks like you didn't have the current version of our project.
All` fly_with `got removed from [data.sql](https://github.com/XMBomb/InComb/blob/687985744af352fd32435a865fb7ecc7b1b6eb86/src/main/sql/data.sql) since they are covered in [test.sql](https://github.com/XMBomb/InComb/blob/master/src/main/sql/test.sql).

**Comment by MangeStrandberg** [comment]
ok... So if I download the latest version it all should be ok then?

**Comment by MangeStrandberg** [comment]
cool project by the way...

**Comment by marcsieber** [comment]
Thank you.
Yes, I guess so. Fly with is in our definition a user which follows another user. But we removed the users from data.sql earlier.

**Comment by mbharanya** [comment]
Please let us know if you need any further help. We're happy to help.

**Comment by MangeStrandberg** [comment]
yeah...

downlöoad the a,ltest veriosn and installed DB and got this message when executin data.sql::
#1452 - Cannot add or update a child row: a foreign key constraint fails (`incomb`.`category_preference`, CONSTRAINT `fk_CategoryPreference_User1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)

**Comment by MangeStrandberg** [comment]
this is what causing this:
INSERT INTO category_preference (user_id, category_id, factor) VALUES(1, 1, 1.0)

**Comment by mbharanya** [comment]
Should be working now, there was still left over test data of the test users...

**Comment by MangeStrandberg** [comment]
:-(

sorry...

#1062 - Duplicate entry '1' for key 'PRIMARY'
caused by:
INSERT INTO incomb.module (id, name_key, image_path, template_path) VALUES(1, "modules.news", "", "")

**Comment by mbharanya** [comment]
You need to remove the current data first. Please execute `schema.sql` again and then try again with `data.sql`

**Comment by MangeStrandberg** [comment]
that did it I think... Thanks :-)
