### ISSUE TITLE
installtaion an design/templates

### ISSUE THREAD

**Issue by MangeStrandberg** [XMBomb/InComb#25]
can u advice on getting the site up? what files, paths etc....

**Comment by mbharanya** [comment]
Can you specify what exactly you're trying to accomplish?
InComb uses custom CSS in `WebContent/css` and no CSS Frameworks other than those in `WebContent/css/lib` for the design and AngularJS for all frontend functionality.

**Comment by MangeStrandberg** [comment]
This is what I get:
![image](https://cloud.githubusercontent.com/assets/25963134/23331744/68d074ca-fb6c-11e6-8c51-f83501f8ea80.png)

**Comment by mbharanya** [comment]
Can you describe your setup? What IDE do you use? What version of Tomcat do you use? Does your IDE support maven and have you downloaded all external libraries?

**Comment by MangeStrandberg** [comment]
i use Netbean 8.0.2 and all i sdownloaded

**Comment by mbharanya** [comment]
Again: What tomcat version are you using? Are you accessing the site on localhost:8080 or similar?
Please describe your exact setup.

**Comment by MangeStrandberg** [comment]
could you advise in how to install using mysql?

**Comment by marcsieber** [comment]
I suggest a installation as a service, so you don't have to start mysql manually at your computer startup.
Use the latest version of mysql with default settings (It should work just fine). 
If you specify username and password you have to adjust those values in your [incomb_config.json.](https://github.com/XMBomb/InComb/blob/master/WebContent/WEB-INF/conf/incomb_config.json)

**Comment by MangeStrandberg** [comment]
Hi... Can u provide step by step installing in liveproduction on mysql... thanks :-)

**Comment by mbharanya** [comment]
It is not in the scope of InComb to teach you how to setup a MySQL and Tomcat server. There are plenty of tutorials on setting up tomcat and mysql on the internet.
InComb requires Java 8,Tomcat 8.5 and MySQL 5.7+
Also maven for dependency management, building and running.
We're all using IntelliJ or Eclipse (the newest version) on Windows for development. Ubuntu 16.04 LTS for production.

You're very welcome to contribute to our project and we'll gladly answer any question concerning the development of new features or bugfixes.
